baseURL = ""
languageCode = "en-us"
title = "@ozorest"
theme = "yinyang"
DefaultContentLanguage = "en"
themesDir = "themes"
publishDir = "public"

[author]
name = "Thiago Ozores"
homepage = "https://joway.io/"

[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1

[languages.pt]
contentDir = "content/pt"
languageName = "Portuguese"
weight = 1

[params]
disqus = "ozorest"
extraHead = ""
mainSections = [ "posts" ]
description = "Father of Luana | DevOps Consultant | Python Developer (in my spare time) | Brazilian"
tagline = "Knowledge not shared is knowledge wasted"

[[params.socials]]
name = "Github"
link = "https://github.com/ozorest"

[[params.socials]]
name = "Twitter"
link = "https://github.com/ozorest"

[[params.socials]]
name = "Linkedin"
link = "https://www.linkedin.com/in/tozores"

[[params.socials]]
name = "RSS"
link = "/index.xml"