baseURL = ""
languageCode = "en-us"
title = "@ozorest"
theme = "yinyang"
DefaultContentLanguage = "en"
themesDir = "themes"
publishDir = "public"

[author]
name = "Thiago Ozores"
homepage = "https://joway.io/"

[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1

[languages.pt]
contentDir = "content/pt"
languageName = "Portuguese"
weight = 1

[params]
disqus = "joway"
extraHead = ""
mainSections = [ "posts" ]

[[params.socials]]
name = "Github"
link = "/index.xml"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://joway.io"
